---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    capability.openshift.io/name: ImageRegistry
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
    include.release.openshift.io/single-node-developer: "true"
    config.openshift.io/inject-tls: "true"
  name: image-registry-operator-config
  namespace: openshift-image-registry
data:
  config.yaml: |-
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
    servingInfo:
      bindAddress: 0.0.0.0:60000
